<?php

namespace xenialdan\PocketAI\component\minecraft;

use xenialdan\PocketAI\component\BaseComponent;
use xenialdan\PocketAI\entitytype\AIEntity;
use xenialdan\PocketAI\entitytype\AIProjectile;

//non-autogenerated!
class _health extends BaseComponent
{
    protected $name = "minecraft:health";
    /** @var int $max Maximum health */
    public $max = 20.0;
    /** @var array|float $value Health or range of health */
    public $value;

    /**
     * Sets the width and height of the Entity's collision box.
     * _health constructor.
     * @param array $values
     */
    public function __construct(array $values = [])
    {
        $this->max = $values['max'] ?? $this->max;
        $this->value = $values['value'] ?? $this->value;

    }

    /**
     * Applies the changes to the mob
     * @param AIEntity|AIProjectile $entity
     */
    public function apply($entity): void
    {
        $entity->setMaxHealth($this->max);
        if (is_array($this->value)) {
            $entity->setHealth(floatval(mt_rand(($this->value["range_min"] ?? 1) * 10, ($this->value["range_max"] ?? 1) * 10) / 10));//TODO random range function
        } else {
            $entity->setHealth($this->value);
        }
    }

    /**
     * Removes the changes from the mob
     * @param AIEntity|AIProjectile $entity
     */
    public function remove($entity): void
    {
        $c = new self;
        $entity->setMaxHealth($c->max);
    }
}
