<?php

namespace xenialdan\PocketAI\component\minecraft;

use xenialdan\PocketAI\component\BaseComponent;
use xenialdan\PocketAI\entitytype\AIEntity;
use xenialdan\PocketAI\entitytype\AIProjectile;

//non-autogenerated
class _identifier extends BaseComponent
{
    protected $name = "minecraft:identifier";
    /** @var string $id The identifier name */
    public $id;

    /**
     * Defines the identifier of the entity
     * _identifier constructor.
     * @param array $values
     */
    public function __construct(array $values = [])
    {
        $this->id = $values['id'] ?? $this->id;
    }

    /**
     * Applies the changes to the mob
     * @param AIEntity|AIProjectile $entity
     */
    public function apply($entity): void
    {
        // TODO: Implement apply() method.
    }

    /**
     * Removes the changes from the mob
     * @param AIEntity|AIProjectile $entity
     */
    public function remove($entity): void
    {
        // TODO: Implement remove() method.
    }
}
