<?php

namespace xenialdan\PocketAI\component\minecraft;

use xenialdan\PocketAI\component\BaseComponent;
use xenialdan\PocketAI\entitytype\AIEntity;
use xenialdan\PocketAI\entitytype\AIProjectile;

//non-autogenerated
class _movement extends BaseComponent
{
    protected $name = "minecraft:movement";
    /** @var array|float $value Health or range of speed */
    public $value;

    /**
     * Sets the width and height of the Entity's collision box.
     * _health constructor.
     * @param array $values
     */
    public function __construct(array $values = [])
    {
        $this->value = $values['value'] ?? $this->value;

    }

    /**
     * Applies the changes to the mob
     * @param AIEntity|AIProjectile $entity
     */
    public function apply($entity): void
    {
        if (is_array($this->value)) {
            $entity->setDefaultSpeed(floatval(mt_rand(($this->value["range_min"] ?? 1) * 10, ($this->value["range_max"] ?? 1) * 10) / 10));//TODO random range function
        } else {
            $entity->setDefaultSpeed($this->value);
        }
    }

    /**
     * Removes the changes from the mob
     * @param AIEntity|AIProjectile $entity
     */
    public function remove($entity): void
    {
        //TODO add remove() function
    }
}
